### ISSUE TITLE
 Не суммируется время игр.

### ISSUE THREAD

**Issue by Ihtiyar91** [MashaRodionova/TeamProject#1]
# Описание
Метод public int sumGenre не суммирует время игр.
# Локация дефекта
https://github.com/MashaRodionova/TeamProject/blob/537caaa142396ab6329a9002d69af82e68f707ff/src/main/java/ru/netology/Player.java#L45 

# Шаги воспроизведения
1. Запустить [тест](https://github.com/MashaRodionova/TeamProject/blob/537caaa142396ab6329a9002d69af82e68f707ff/src/test/java/ru/netology/PlayerTest.java#L9) в IDEA
1. Посмотреть вывод в консоли

*Ожидаемый результат:* 3
*Фактический результат:* 0

# Скриншот
![2022-07-20_14-44-20](https://user-images.githubusercontent.com/103990001/179974220-48f82745-2436-4175-82c8-833cb56b1482.png)

# Окружение
* **Операционная система:** Windows 10 Pro
*  **IDE:** IntelliJ IDEA 2020.2 (Community Edition)
*  **Java:** OpenJDK 11

**Comment by MashaRodionova** [comment]
в методе sumGenre баг не обнаружен. Баг обнаружен посредством отладчика в методе play (не суммирует время игры), который ты используешь в тесте shouldSumGenreIfOneGame() [строка](https://github.com/MashaRodionova/TeamProject/blob/537caaa142396ab6329a9002d69af82e68f707ff/src/test/java/ru/netology/PlayerTest.java#L15). Метод play исправила, тест на метод sumGenre проходит.

**Comment by Ihtiyar91** [comment]
[Bug fixed (configurate method PLAY), close issue](https://github.com/MashaRodionova/TeamProject/commit/e90156ae2520b34b1f5709cd36710ee1313347b9) https://github.com/MashaRodionova/TeamProject/issues/1
