### ISSUE TITLE
Отсутствие в методе исключения RuntimeException.

### ISSUE THREAD

**Issue by Ihtiyar91** [MashaRodionova/TeamProject#2]
# Описание
Метод  public int play не выкидывает RuntimeException.
# Локация дефекта
https://github.com/MashaRodionova/TeamProject/blob/87d96a6ed8cb4b412e00cb0a30310bab0ae0b65d/src/main/java/ru/netology/Player.java#L36

# Шаги воспроизведения
1. Запустить [тест](https://github.com/MashaRodionova/TeamProject/blob/9ddfbbaf34ba6a11c80c96ca19525bd7c28c4257/src/test/java/ru/netology/PlayerTest.java#L42) в IDEA
1. Посмотреть вывод в консоли

*Ожидаемый результат:* Отображается сообщение RuntimeException.
*Фактический результат:* org.opentest4j.AssertionFailedError: Expected java.lang.RuntimeException to be thrown, but nothing was thrown.

# Скриншот
![2022-07-20_17-32-13](https://user-images.githubusercontent.com/103990001/180008744-d61cd9e6-5c95-416e-8d65-d2342058af74.png)

# Окружение
* **Операционная система:** Windows 10 Pro
*  **IDE:** IntelliJ IDEA 2020.2 (Community Edition)
*  **Java:** OpenJDK 11

**Comment by MashaRodionova** [comment]
в тесте shouildThrowRunTimeException() для ассерта в [строке](https://github.com/MashaRodionova/TeamProject/blob/dfc53a3553819fd1c5c6b00c75eb3d71db3ce67e/src/test/java/ru/netology/PlayerTest.java#L40) в метод play ты передаешь аргументом game3. Тк такой объект уже выше добавлен, тест пройдет не по запланированному тобой сценарию

**Comment by Ihtiyar91** [comment]
Тест shouildThrowRunTimeException() подправил

**Comment by Ihtiyar91** [comment]
53fac06
