### ISSUE TITLE
Некорректная работа метода mostPlayerByGenre 

### ISSUE THREAD

**Issue by Ihtiyar91** [MashaRodionova/TeamProject#3]
# Описание
 Метод public Game mostPlayerByGenre возвращает null при установленных играх.
# Локация дефекта
https://github.com/MashaRodionova/TeamProject/blob/87d96a6ed8cb4b412e00cb0a30310bab0ae0b65d/src/main/java/ru/netology/Player.java#L59

# Шаги воспроизведения
1. Запустить [тест](https://github.com/MashaRodionova/TeamProject/blob/23c941887474567e070ffeb0693d1de04f97cf15/src/test/java/ru/netology/PlayerTest.java#L65) в IDEA
1. Посмотреть вывод в консоли

*Ожидаемый результат:* Игра1
*Фактический результат:* null
# Скриншот

![2022-07-20_17-43-02](https://user-images.githubusercontent.com/103990001/180011299-ab4c2743-919f-4636-9567-dc619a4b199a.png)

# Окружение
* **Операционная система:** Windows 10 Pro
*  **IDE:** IntelliJ IDEA 2020.2 (Community Edition)
*  **Java:** OpenJDK 11

**Comment by MashaRodionova** [comment]
в [тесте ](https://github.com/MashaRodionova/TeamProject/blob/87d96a6ed8cb4b412e00cb0a30310bab0ae0b65d/src/test/java/ru/netology/PlayerTest.java#L60-L62)ты пытаешься сравнить переменную String и объект типа Game

**Comment by Ihtiyar91** [comment]
Метод mostPlayerByGenre принимает жанр и возвращает игру этого жанра, в которую играли больше всего
     Если в игры этого жанра не играли, возвращается null . В этом тесте я сравниваю игры .  Он просто не реализован , при реализации объект типа Game поменяй на String.(public String mostPlayerByGenre(String genre)).Тест исправлен под этот метод.

**Comment by MashaRodionova** [comment]
@Ihtiyar91 , мы не методы под тесты пишем, а тесты на методы. В описании сказано, что метод принимает жанр (то есть параметр типа String), а возвращает игру (то есть объект типа Game). 
и в своем тесте ты сравнивал разные типы (String и Game). Насколько я знаю, в ассерт необходимо подавать сущности одного типа

**Comment by Ihtiyar91** [comment]
В описании указано что возвращает игру этого жанра, название игр у нас тоже параметр типа String.

**Comment by MashaRodionova** [comment]
Да, возвращает ИГРУ этого жанра. А игра у нас - это объект типа Game с полями разных типов (в том числе с полем жанра типа String)

**Comment by Ihtiyar91** [comment]
Так в этом и проблема. Есть объект типа Game c разными полями, а метод mostPlayerByGenre должен возвращать только название игры. В проекте ошибки же в методах, поэтому мы их правим чтоб тесты заработали.

**Comment by MashaRodionova** [comment]
Смотри, нам была дана [болванка метода с комментарием](https://github.com/MashaRodionova/TeamProject/blob/9ddfbbaf34ba6a11c80c96ca19525bd7c28c4257/src/main/java/ru/netology/Player.java#L57-L61). 
Твой тест изначально неверный и не пройдет даже при верном методе, как я понимаю. В  первой версии [теста](https://github.com/MashaRodionova/TeamProject/blob/87d96a6ed8cb4b412e00cb0a30310bab0ae0b65d/src/test/java/ru/netology/PlayerTest.java#L60-L62) ты в переменную expected кладешь значение типа String, а в переменную actuale значение типа Game. А потом ассертом пытаешься их сравнить. Они априори не должны быть равны. Ты можешь сравнить поле НАЗВАНИЕ объекта типа Game с переменной expected типа String - это сравнимые типы.
1. В задании написано, что у некоторых методов отсутствует реализация. То есть можно предположить, что мы вольны менять написанную преподавателем болванку (например, название метода, тип возвращаемого значение или тип параметра, да или вообще тип самого метода). В целом я бы и сама типом возвращаемого значения сделала, например, мапу, чтобы выводить несколько объектов игры, если мы будем предусматривать такой сценарий (сейчас выводится первый из равных по жанру и времени игры). Но пока в дискорд @pjanoh не ответил мне, можно ли так делать, или же мы ограничены условиями задачи.
2. В комментарии к заданию написано "Метод принимает **жанр** и возвращает **игру** этого жанра, в которую играли больше всего. Если в игры этого жанра не играли, возвращается null". Думаю, логично предположить, что если бы преподаватель хотел, чтобы метод возвращал название игры, то он так бы и указал (как в случае с жанром). Ну и в болванке типом возвращаемого значения прописал бы String.

**Comment by Ihtiyar91** [comment]
Исправил тест на метод

**Comment by Ihtiyar91** [comment]
[3ed2948](https://github.com/MashaRodionova/TeamProject/commit/3ed29483bed5c4a1a7b909ac1ec6618f2e14e07b)
