### ISSUE TITLE
Метод addPlayTime не суммирует время для одного и того же игрока

### ISSUE THREAD

**Issue by MashaRodionova** [MashaRodionova/TeamProject#5]
### Описание
При добавлении в каталог playedTime игрока с уже имеющимся в каталоге именем , метод не суммирует время с прошлым значением
### Локализация дефекта
https://github.com/MashaRodionova/TeamProject/blob/79b8743378a8a287a2b1f4b9bb68587217037bfc/src/main/java/ru/netology/GameStore.java#L48
### Шаги воспроизведения
1. Открыть [код програмы](https://github.com/MashaRodionova/TeamProject/blob/79b8743378a8a287a2b1f4b9bb68587217037bfc/src/test/java/ru/netology/GameStoreTest.java#L56-L70)
2. Поставить точку останова на [строке](https://github.com/MashaRodionova/TeamProject/blob/79b8743378a8a287a2b1f4b9bb68587217037bfc/src/test/java/ru/netology/GameStoreTest.java#L63)
3. Запустить отладчик
4. Посмотреть вывод в консоли

_Ожидаемый результат:_ в мапе playedTime у Ключа "Masha" значение 10
_Фактический результат:_ в мапе playedTime у Ключа "Masha" значение 8

### Скриншот
![image](https://user-images.githubusercontent.com/98262360/180101447-f577111c-7b99-4ca8-add9-281479a1193d.png)

### Окружение

- **Операционная система:** Windows 10 Pro

- **IDE**: IntelliJ IDEA 2020.2 (Community Edition)

- **Java:** OpenJDK 11

**Comment by Ihtiyar91** [comment]
[75c49ef](https://github.com/MashaRodionova/TeamProject/commit/75c49efe373c41d063f161c97868ab00b4cd4819)
