### ISSUE TITLE
Некорректная работа метода getMostPlayer при одинаковом времени игры у всех игроков в каталоге

### ISSUE THREAD

**Issue by MashaRodionova** [MashaRodionova/TeamProject#6]
### Описание
Если каталог playedTime заполнен игроками с одинаковым временем игры, метод выдает результатом объект игрока, зафиксированного в первой итерации цикла 
### Локализация дефекта
https://github.com/MashaRodionova/TeamProject/blob/79b8743378a8a287a2b1f4b9bb68587217037bfc/src/main/java/ru/netology/GameStore.java#L63-L65
### Шаги воспроизведения
1. Открыть [код програмы](https://github.com/MashaRodionova/TeamProject/blob/79b8743378a8a287a2b1f4b9bb68587217037bfc/src/test/java/ru/netology/GameStoreTest.java)
2. Запустить [тест shouldGetMostPlayer3()](https://github.com/MashaRodionova/TeamProject/blob/79b8743378a8a287a2b1f4b9bb68587217037bfc/src/test/java/ru/netology/GameStoreTest.java#L94-L103)
3. Посмотреть вывод в консоли

_Ожидаемый результат:_ null
_Фактический результат:_ Petya
### Скриншот
![image](https://user-images.githubusercontent.com/98262360/180102689-ed5736e0-d199-4bd2-889e-f06902fa3617.png)

### Окружение

- **Операционная система:** Windows 10 Pro

- **IDE**: IntelliJ IDEA 2020.2 (Community Edition)

- **Java:** OpenJDK 11

**Comment by Ihtiyar91** [comment]
В данном случаи бага нет , метод недолжен возвращать null при одинаковой наигранности часов у игроков.

**Comment by MashaRodionova** [comment]
@Ihtiyar91 , да, ты прав, тест мой некорректен. Я пока не знаю, как без геттера корректно задать ожидаемое значение, чтобы протестировать этот сценарий . Задала вопрос в Дискорд, жду. Если есть идеи, направь, плз.
