### ISSUE TITLE
Метод public int sumGenre не суммирует время игр одного жанра.

### ISSUE THREAD

**Issue by Ihtiyar91** [MashaRodionova/TeamProject#9]
# Описание
При добавлении игр одного жанра метод public int sumGenre не суммирует проигранное время.
# Локация дефекта
https://github.com/MashaRodionova/TeamProject/blob/cb8d9d840829f5bc26350081b590e788c516e1e1/src/main/java/ru/netology/Player.java#L45

# Шаги воспроизведения
1. Запустить [тест](https://github.com/MashaRodionova/TeamProject/blob/cb8d9d840829f5bc26350081b590e788c516e1e1/src/test/java/ru/netology/PlayerTest.java#L22) в IDEA
1. Посмотреть вывод в консоли

*Ожидаемый результат:* 8
*Фактический результат:* 0

# Скриншот
![2022-07-21_18-03-11](https://user-images.githubusercontent.com/103990001/180248339-adba9017-cb95-494e-a078-afb5e8af93c6.png)

# Окружение
* **Операционная система:** Windows 10 Pro
*  **IDE:** IntelliJ IDEA 2020.2 (Community Edition)
*  **Java:** OpenJDK 11

**Comment by Ihtiyar91** [comment]
Не вижу никаких изменений  методе.

**Comment by MashaRodionova** [comment]
@Ihtiyar91 , может, ты не залил себе изменения из ветки player? Все перепроверила - на гитхаб в ветку player изменения запушены. В последнем коммите, который прикреплен к этой ишке, показаны изменения

**Comment by Ihtiyar91** [comment]
Теперь вижу

**Comment by Ihtiyar91** [comment]
[6349afa](https://github.com/MashaRodionova/TeamProject/commit/6349afa783b0cb95bf3e729744f3b2af290196dc)
